### PR TITLE
Convert static html pages to Jekyll

### PR DESCRIPTION
**Pull request by andeersg**
First of all, I really like this idea to encourage people to contribute to open source.

I saw that it was [mentioned](https://github.com/yourfirstpr/yourfirstpr.github.io/issues/4) to make this site a Jekyll site.

So I thought I could create a small pull request that does this.

It could probably split up the files even more, but at least it's a start :)

* Move the outer tags to `default.html`-layout.
* Move the footer content to a included file.
* Add some variables to `_config.yml`.

If something is unclear I can explain more :)

### CODE REVIEW

**Comment by Charlotteis** [comment]
Hey @andeersg! Thank you so much for the effort you've made, I hope it was fun. I will go through this soon, but I see no reason why I won't merge this.

I think all that needs to be done now is to write instructions on how to run this locally, and how to work with it: but I am happy to do this myself when I get the time.

Have a great day ☀

**Comment by andeersg** [comment]
So nice that you liked it :smile: 

That sounds great, I can add a small section to the readme about running Jekyll locally at least.

**Comment by matheussampaio** [comment]
Can we have this merged?

**Comment by Charlotteis** [comment]
@matheussampaio Hi there. I am very busy right now, so I will be reviewing this and merging this when I have the time. Sorry.

**Comment by BPScott** [comment]
Rather than relying on a globally installed version of Jekyll, it would be preferable to use a `Gemfile` and Bundler to lock the version of Jekyll for this project. This is because the globally-installed version of Jekyll that somebody has installed may be different from the version that GitHub uses to deploy pages and from other people who develop work on the site. This could lead to unexpected behaviour where somebody could claim "it works for me locally" but the site does not build on GitHub as that person's version of Jekyll is different.

Fortunately [GitHub provides a gem](https://help.github.com/articles/using-jekyll-with-pages/#installing-jekyll) that details what version of Jekyll they use so that people can be sure what they're developing locally shall work on GitHub pages. The Gemfile would end up looking like:

```ruby
source 'https://rubygems.org'
gem 'github-pages'
```

And the installation instructions would be:

Run `bundle install` to install all dependancies.
Run `bundle exec jekyll serve` to run the server.

The first time you run `bundle install` after creating the `Gemfile` it shall also create a `Gemfile.lock`, which should also be committed as part of this PR.

**Comment by andeersg** [comment]
Hi, I'm not that familiar with Ruby, so I forgot that part, but I will add it :)

**Comment by Charlotteis** [comment]
Cheers @BPScott!

**Comment by BPScott** [comment]
Not a problem @andeersg :) I appreciate that getting started with a new ecosystem is almost always a sheer cliff rather than a learning curve. Thank you for taking the time to look into Ruby and contribute.

**Comment by Kriesse** [comment]
Nice work converting the site to Jekyll!
@Charlotteis Would a co-review of the PR be helpful to take some workload off of you?

If yes: LGTM from my side – I just reviewed and all looks good to me. 
Here’s what I did in detail:
* Checked out the branch
* :white_check_mark: Followed the README instructions to get the site running locally with jekyll. Worked great, instructions are clear and beginner-friendly.
* :white_check_mark: Reviewed the site in the browser, compared to the master branch, all looks like expected.
* :white_check_mark: Reviewed all commits separately for typos / unintended copy changes / broken links… looks all good!

Only suggestion from my end would be to add a sentence to the README for people who are absolutely new to jekyll, explaining what it is and where to learn more (e.g. http://jekyllrb.com/).
cc @andeersg

**Comment by Charlotteis** [comment]
Thank you @Kriesse, this is extremely kind of you. I am **so** sorry I haven't gotten to this STILL, this is entirely my fault as my workload is immense right now. Good news is I have some time off this week! This will b much easier to review now that I have had a review from Kriesse as well. :bow:

**Comment by Charlotteis** [comment]
Hi @andeersg. Once again, I am truly sorry this took so long. Who knew life could get in the way so much? I should have given this attention from the outset, because THIS.IS.GREAT.

THANK YOU.
Merging. :shipit:

**Comment by andeersg** [comment]
:+1: :+1:

**Pull request merged**
