### PR TITLE
Updates to landing page/visual content

### PR DESCRIPTION
**Pull request by yasinS**
Hi,

I've forked the repo and made a few commits revising the landing page and visuals. This is a brilliant initiative, great that the Code of Conduct and blog are set up too :)

Hope these edits are okay!

### CODE REVIEW

**Comment by Charlotteis** [comment]
@yasinS this is fantastic!

If you could fix the merge conflict in `index.html`, I'd be very happy to merge this.

**Comment by yasinS** [comment]
Thank you @Charlotteis, merge conflict resolved! Hope to continue contributing with some more commits soon.

**Comment by Charlotteis** [comment]
@yasinS merged! Thanks soooo much.

**Comment by yasinS** [comment]
@Charlotteis No problem, thank you again :)

**Pull request merged**
