### PR TITLE
Website Optimize

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by Jameskmonger** [comment]
I don't think that moving the css from being locally hosted to being hosted on a CDN will optimise the performance of the site, @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@Jameskmonger use cloudflare/cdnjs cdn in most cases will be faster then github.io I think

**Comment by nickcolley** [comment]
Best way is to measure it, you'd want to measure locally compressed vs cdn compressed.
By looking at it at face value, this will be quicker than current since the file is compressed.

**Comment by Charlotteis** [comment]
Happy to give it a go, thanks @PeterDaveHello.

**Pull request merged**
